name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v4
      with:
        activate-environment: assemblyuploader
        python-version: ${{ matrix.python-version }}

    - name: Install the webcli
      shell: bash -el {0}
      run: conda install -c bioconda ena-webin-cli

    - name: Install additional packages
      shell: bash -el {0}
      run: pip install .[test]

    - name: Run pytest
      shell: bash -el {0}
      run: pytest
